sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: lGYxokgOQ60VCA7Z5p8PZVNIhDnSgmAdqqt4hHtx/7lsECYHj/qtJ5BRCmg70Meb7wWKyTU/VEVMpSHmigmucMsDtjMgCHGVNoLKz5uvJww27HhVnSeII3UWa5mnFne2E617WIYJy/U3WUMk9+rdrNCRe+sA9cbaD1pZ2Ku6mNVdvLcHy06tDUhxGE/Ik/BcCz1LseKYIzq+KH5wRi/tF/MTCBJzLe5fTO9OLsxFdf71SltSmPkodoSkKqF8+0sBURbs3bxMTrMPUEpf5TmuTuEoI4gGr0rcrBgTCi+SaMRvVE7ubA9UKIe/JK+YfcIZ16OGyJKXA+TbVNAUI+nJ2IYz71HAmP/fGdgYp4Ze73XerF1EDS0Yjh4KhBtZZzPGgXIopMgWaBiHlv6vK0tzzkX0CPtaw//z5Y52b41RJswCC9SMnnNYU1FpQYrUv+dK0Gjm48cSYDaT4KKUyE/ssfee6L6JfNER+WvTW4d70rUtvG8L/Ea52oJNcntFq39cn+379HKukr8+4iXKJ36GK3S135HAQ3Uma+IOVOWAA8S+qiPIXKzSHKETPZMHS2GF2A5HS0YcKvbJ5E6GuKVP/Wa6HEan8gSVZJrJ4UHmZ27w+5AF8GTDLClBBvDi90QSpMCImbJO4Ru/GuiykxQ/T0hrl/wD/AfX3MKMPBFEOMw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Wild-Wales-Its-People-Language-and-Scenery_648
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy